[versions]
mod = "0.1.0"
minecraft = "1.21"
yarn = "9"
unimined = "1.3.4"
neo = "147"
fabric-loader = "0.16.0"

# Mods
fabric-api = "0.100.8+1.21"
[libraries]
# Mods
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
[plugins]
unimined = { id = "xyz.wagyourtail.unimined", version.ref = "unimined" }