[versions]
mod = "0.1.0"
minecraft = "1.21"
yarn = "1.21+build.9"
yarn-mappings-patch-neoforge = "1.21+build.4"
neo = "21.0.139-beta"
fabric-loader = "0.16.0"

fabric-api = "0.100.7+1.21"
architectury-api = "13.0.6"
[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
yarn-patch = { group = "dev.architectury", name = "yarn-mappings-patch-neoforge", version.ref = "yarn-mappings-patch-neoforge" }

neo = { group = "net.neoforged", name = "neoforge", version.ref = "neo" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }